### ISSUE TITLE
Transparent Viewmodels And Scoreboard.

### ISSUE THREAD

**Issue by SsunSSet** [nimtra/mkHUD#13]
Is there any chance you can make a build-in transparent viewmodel setting? caz i like them and i love your hud and the files doesnt seems right if i do that myself. thanks.

And, is there a way that i can make the scoreboard bigger just like normal ones?

**Comment by kmarcie** [comment]
Feature isn't planned sorry, if you want to add the viewmodels yourself it's relatively easy and it only involves editing one file which would be in the hud folder > scripts > HudLayout.res. https://www.teamfortress.tv/21928/transparent-viewmodels-in-any-hud It also involves setting some settings yourself that the HUD can't set on it's own.

Not exactly sure what you mean by enlarging the scoreboard. It's pretty large as is - I made it this way so that it wouldn't interfere with gameplay too much

Just cleaning up github entries i kinda forgot that this existed lol
