### ISSUE TITLE
Vaccinator "%" is invisible.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [nimtra/mkHUD#9]
https://i.imgur.com/zSv4YKI.png
I have no idea why this happens. Especially because others mediguns weapons don't have this issue.
*Tested on a 21:9 3440x1440 configuration*

**Comment by kmarcie** [comment]
Unfortunately this is due to the way that the game interacts with drop shadows. Drop shadows aren't natively added and don't get automatically removed when they're not in use. 

The vaccinator doesn't rely on a charge percentage, rather it uses a meter of 0-4 instead to display the number of charges. Because the dropshadow doesn't properly track this, it doesn't get rid of the percentage and it doesn't track it properly. It's just one of those trade-offs for having nice shadows. I messed with this extensively but couldn't find much of a resolution to it. Sorry bout that
